### ISSUE TITLE
Support air conditioners (qt)

### ISSUE THREAD

**Issue by taneliang** [0x5e/homebridge-tuya-platform#107]
Hi, I bought an IR remote to control my air conditioner, but both the IR remote and the configured air conditioner are showing up in the Apple Home app as unsupported devices and they aren't showing up at all in Homebridge's accessories list. It would be great if we could support air conditioners in this plugin.

In tuya's devices list, the product name is "空调" and the product category is "qt".

Thanks for all your work on this plugin ❤️

**Comment by 0x5e** [comment]
IR AC and AC are different category, anyway I will do in 1.7.0, IR device is a big thing to support.

**Comment by 0x5e** [comment]
the category `qt` means `other`（其他）, it's a custom IR device type.
for IR AC device `infrared_ac`, it will appear 3 accessories AirConditioner, Dehumidifier, Fan because HomeKit AirConditioner don't have dehumidifier mode and fan mode.
for other device type, it will appear as multiple switches.

the IR AC command is stateful, others are stateless.
